# Generated by Django 5.2.6 on 2025-09-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
