# Generated by Django 5.2.6 on 2025-10-09 04:58

import baseapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_client_project_client_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to=baseapp.models.media_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='baseapp.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.employee')),
            ],
        ),
    ]
