# Generated by Django 5.2.6 on 2025-10-09 07:36

import baseapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0009_projectcommentmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='projectMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=baseapp.models.media_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='baseapp.projectcommentmedia')),
            ],
        ),
    ]
