# Generated by Django 5.2.6 on 2025-10-09 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_projectmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcommentmedia',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
