# Generated by Django 5.2.6 on 2025-10-10 13:43

import baseapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_alter_projectcommentmedia_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskCommentMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='baseapp.task')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='baseapp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='tasktMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=baseapp.models.media_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_media_files', to='baseapp.taskcommentmedia')),
            ],
        ),
    ]
