# Generated by Django 5.2.6 on 2025-10-16 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0014_taskfinalcode_tasktfinalmedia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskfinalcode',
            old_name='comment',
            new_name='code',
        ),
    ]
