# Generated by Django 5.2.6 on 2025-10-16 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_rename_comment_taskfinalcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasktfinalmedia',
            old_name='comment',
            new_name='code',
        ),
    ]
