# Generated by Django 5.2.6 on 2025-10-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0016_rename_comment_tasktfinalmedia_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in progress', 'In Progress'), ('under review', 'Mark completed'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
    ]
